name: aspose_words_cloud
description: This package allows you to work with Aspose.Words Cloud REST APIs in your Dart applications quickly and easily, with zero initial cost.
version: 25.12.0
homepage: https://github.com/aspose-words-cloud/aspose-words-cloud-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.1
  uuid: ^4.4.2
  pointycastle: ^3.9.1
  lints: ^4.0.0
  convert: ^3.1.1

dev_dependencies:
  test: ^1.25.5